from openai import OpenAI
from langgraph.graph import StateGraph, START, END
from typing_extensions import TypedDict
from dotenv import load_dotenv
import logging


logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

load_dotenv()

class State(TypedDict):
    query : str
    llm_result : str | None
    error : str | None

class QueryWithOpenAI:
    def __init__(self):
        """Initializes the OpenAI client and builds the graph."""
        try :
            self.client = OpenAI()
            self.graph = self._build_graph()
        except Exception as e:  
            logger.error(f"Error initializing openai clienr : {e}")
            raise 

    def _build_graph(self):
        """ Greaph Building here""" 
        print("⚠️ start build graph",self)

        graph_builder = StateGraph(State)

        "Node For go to chat bot"
        graph_builder.add_node("chat_with_openai",self.chat_with_openai)
        

        " Adges for run graph"

        graph_builder.add_edge(START,"chat_with_openai")
        graph_builder.add_edge("chat_with_openai",END)
        return graph_builder.compile()

    def chat_with_openai(self,state:State) -> State:

        """ Node to interact with the OpenAI LLM"""
        query = state['query']
        try:
            response= self.client.chat.completions.create(
                # print('yes2'),
                # model= "gpt-4.1",
                model= "gpt-4.1-nano",
                messages=[{"role":"user","content":query}]
            )
            print(f"OK:{response.choices[0].message.content}")
            if response:
                state['llm_result'] = response.choices[0].message.content
                state['error'] = None
            else:
                state['llm_result'] = "Sorry, I could not generate a response."
                state['error'] = "No content generated by the model."
        except:
            logger.error("Error generating content with openai")
            state['llm_result'] = None
            state['error'] = "Error generating content with OpenAI."    
        return state     
    
    def run(self,query:str) -> State:
        _state : State = {
        'query' : query,
        'llm_result' : None,
        'error' : None
        }
        """Run the graph with the provided query."""
        try:
            print('yes')
            result= self.graph.invoke(_state)
            return result
        except Exception as e:
            logger.error(f"Error invoking the graph: {e}")
            return {"query": query,"llm_result": None, "error": str(e)}

def main():
    try:
        input_query = input("Enter your query: ")
        query_with_openai = QueryWithOpenAI()
        result = query_with_openai.run(input_query)

        if result.get('error'):
            print(f"An error occurred : {result['error']}")
        elif result.get('llm_result'):
            print(f"Response from OpenAI: {result['llm_result']}")

    except Exception as e:
        logger.error(f"An error occurred in main: {e}") 
        print(f"ERROR : {e}")      

if __name__ == "__main__":
    main()
